ekf_filter_node_odom:
  ros__parameters:
    use_sim_time: true
    frequency: 30.0
    sensor_timeout: 0.1
    two_d_mode: true
    publish_tf: true
    map_frame: map
    odom_frame: odom
    base_link_frame: base_footprint 
    world_frame: odom

    odom0: /odom
    # 🔥 로컬 EKF: 바퀴는 전진 속도(v_x)만 믿습니다. (절대 위치 X, Y 무시)
    odom0_config: [false, false, false,
                   false, false, false,
                   true,  false, false,   # <--- v_x (전진 속도)
                   false, false, false,
                   false, false, false]
    odom0_queue_size: 10
    odom0_differential: false 

    imu0: /sensing/imu/imu_data
    # 🔥 로컬 EKF: 방향은 오직 IMU의 Yaw와 각속도를 믿습니다.
    imu0_config: [false, false, false,
                  false, false, true,    # <--- 절대 방향 (Yaw)
                  false, false, false,
                  false, false, true,    # <--- 회전 속도 (v_yaw)
                  false, false, false]
    imu0_queue_size: 10
    imu0_differential: false
    imu0_relative: false 

ekf_filter_node_map:
  ros__parameters:
    use_sim_time: true
    frequency: 30.0
    sensor_timeout: 0.1
    two_d_mode: true
    publish_tf: true
    map_frame: map
    odom_frame: odom
    base_link_frame: base_footprint 
    world_frame: map

    odom0: /odom
    # 글로벌 EKF: 바퀴의 전진 속도(v_x)와 회전 속도(v_yaw)만 사용
    odom0_config: [false, false, false,
                   false, false, false,
                   true,  false, false,
                   false, false, true,
                   false, false, false]
    odom0_queue_size: 10
    odom0_differential: false 

    imu0: /sensing/imu/imu_data
    # 글로벌 EKF: IMU 방향(Yaw) 사용
    imu0_config: [false, false, false,
                  false, false, true,
                  false, false, false,
                  false, false, false,
                  false, false, false]
    imu0_queue_size: 10
    imu0_differential: false
    imu0_relative: false 

    odom1: /odometry/gps      
    # 글로벌 GPS: 맵 상의 절대 위치(X, Y) 켜기! (시뮬레이션이므로 Yaw는 false 유지)
    odom1_config: [true,  true,  false,
                   false, false, false,
                   false, false, false,
                   false, false, false,
                   false, false, false]
    odom1_queue_size: 10
    odom1_differential: false

navsat_transform:
  ros__parameters:
    use_sim_time: true
    frequency: 30.0
    delay: 3.0 
    magnetic_declination_radians: 0.0 
    yaw_offset: 0.0
    zero_altitude: true
    broadcast_cartesian_transform: true
    publish_filtered_gps: true
    use_odometry_yaw: false 
    wait_for_datum: true
    datum: [36.61002559225, 127.28772570583, 0.0]
    base_link_frame: base_footprint
    world_frame: map